#spring.application.name=picpaysimplificado
#spring.datasource.url=jdbc:postgresql://localhost:5432/users
#spring.datasource.username=postgres
#spring.datasource.password=usertest
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#server.port=8081

spring.application.name=picpaysimplificado
spring.datasource.url=jdbc:mysql://localhost:3306/picpay
spring.datasource.username=root
spring.datasource.password=Isa8081
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
server.port=8080
spring.flyway.enabled=true